#!/bin/bash
# list-scripts.sh - Afficher la liste des scripts disponibles

echo "📜 Scripts de configuration disponibles pour z3-auth :"
echo ""
echo "🎯 Script principal :"
echo "   ./setup-modular.sh          - Exécute tous les scripts dans l'ordre"
echo ""
echo "🔧 Scripts individuels :"
echo "   scripts/setup-directories.sh - Créer la structure des répertoires"
echo "   scripts/create-core-files.sh - Créer les fichiers principaux (lib.rs, error.rs, etc.)"
echo "   scripts/create-modules.sh    - Créer les modules spécialisés (user, password, token, etc.)"
echo "   scripts/setup-cargo.sh       - Configurer Cargo.toml avec dépendances et métadonnées"
echo "   scripts/create-docs.sh       - Créer la documentation (README, CHANGELOG, CONTRIBUTING)"
echo "   scripts/setup-ci.sh          - Configurer GitHub Actions CI"
echo "   scripts/create-tests.sh      - Créer les tests, exemples et benchmarks"
echo ""
echo "💡 Usage :"
echo "   ./setup-modular.sh                    # Configuration complète"
echo "   ./scripts/setup-directories.sh        # Seulement les répertoires"
echo "   ./scripts/create-core-files.sh        # Seulement les fichiers principaux"
echo "   # etc..."
echo ""
echo "✨ Chaque script peut être exécuté indépendamment selon tes besoins !"
