[package]
name = "web_server"
version = "0.1.0"
edition = "2024"

[dependencies]
narangcia-cryptic-auth = { path = "../..", features = ["web"] }
tokio = { version = "1.47.1", features = ["full"] }
env_logger = "0.11.8"
