[package]
name = "cli_example"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
narangcia-cryptic = { path = "../..", features = ["bare"] }
tokio = { version = "1.46.1", features = ["full"] }
